namespace KartQueryTools.Packets
{
	// https://github.com/STJr/Kart-Public/blob/master/src/d_clisrv.h#L53
	internal enum packettype_t : byte
    {
		PT_NOTHING,
		PT_SERVERCFG,
        PT_CLIENTCMD,
		PT_CLIENTMIS,
		PT_CLIENT2CMD,
		PT_CLIENT2MIS,
		PT_NODEKEEPALIVE,
		PT_NODEKEEPALIVEMIS,
		PT_SERVERTICS,
		PT_SERVERREFUSE,
		PT_SERVERSHUTDOWN,
		PT_CLIENTQUIT,
		PT_ASKINFO,
		PT_SERVERINFO,
		PT_PLAYERINFO,
		PT_REQUESTFILE,
		PT_ASKINFOVIAMS,
        PT_RESYNCHEND,
		PT_RESYNCHGET,
        PT_CLIENT3CMD,
		PT_CLIENT3MIS,
		PT_CLIENT4CMD,
		PT_CLIENT4MIS,
		PT_BASICKEEPALIVE,
		PT_CANFAIL,
		PT_FILEFRAGMENT = PT_CANFAIL,
		PT_TEXTCMD,
		PT_TEXTCMD2, 
		PT_TEXTCMD3,
		PT_TEXTCMD4,
		PT_CLIENTJOIN,
		PT_NODETIMEOUT,
		PT_RESYNCHING,
		PT_TELLFILESNEEDED,
		PT_MOREFILESNEEDED,
		PT_PING,
		NUMPACKETTYPE
    }
}